version: '3'

services:
  web:
    build: docker/php
    image: laravel
    depends_on:
      - redis
      - phpmyadmin
    volumes:
     - ./:/application

  nginx:
    image: nginx:alpine
    build: docker/nginx
    ports:
      - "8000:80"
    depends_on:
      - web
  
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions

volumes:
  db-data: